export const logo = {height: "32px", margin: "16px", fontSize:"1rem", color:"#fff"}
export const header = { background: '#fff', padding: 0 }
export const trigger = {fontSize: "18px", lineHeight: "64px", padding: "0 24px", cursor: "pointer", color: "#001529"}
export const content = { margin: '24px 16px', padding: 24, background: '#fff'}
export const exampleMenuItemNotFocused = {color: '#fff',background:"#001529",paddingTop:"0.6rem", height:"2rem",width:"100%"}
export const exampleMenuItemFocused = {...exampleMenuItemNotFocused,background:"#1890ff"}
export const exampleAsistenteOff = {...exampleMenuItemNotFocused,background:"#334454"}
export const exampleAsistenteOn = {color: '#fff',paddingTop:"0.6rem", height:"2rem",width:"100%"}
export const comandoName = {marginTop:"0.4rem"}
